
import { Client, LegalCase, Appointment, CaseStatus } from './types';

export const mockClients: Client[] = [
  {
    id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '(555) 123-4567',
    joinedAt: new Date(2023, 3, 15),
    casesCount: 2,
  },
  {
    id: '2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '(555) 987-6543',
    joinedAt: new Date(2023, 5, 22),
    casesCount: 1,
  },
  {
    id: '3',
    name: 'Robert Johnson',
    email: 'robert.johnson@example.com',
    phone: '(555) 456-7890',
    joinedAt: new Date(2023, 6, 8),
    casesCount: 3,
  },
];

export const mockLawyerCases: LegalCase[] = [
  {
    id: '1',
    clientId: '123',
    clientName: 'John Doe',
    title: 'Contract Review - Johnson Corp',
    description: 'Review of the employment contract with Johnson Corporation',
    category: 'Contract Law',
    status: CaseStatus.IN_PROGRESS,
    priority: 'medium',
    dueDate: new Date(2025, 5, 15),
    documents: [],
    createdAt: new Date(2023, 5, 12),
    updatedAt: new Date(2023, 6, 1),
  },
  {
    id: '2',
    clientId: '123',
    clientName: 'Jane Smith',
    title: 'Trademark Registration - TechBrand',
    description: 'Assistance with trademark registration for new product line',
    category: 'Intellectual Property',
    status: CaseStatus.NEW,
    priority: 'high',
    dueDate: new Date(2025, 5, 20),
    documents: [],
    createdAt: new Date(2023, 7, 20),
    updatedAt: new Date(2023, 7, 20),
  },
  {
    id: '3',
    clientId: '456',
    clientName: 'Robert Johnson',
    title: 'Property Dispute - 123 Main St',
    description: 'Boundary dispute with neighboring property',
    category: 'Real Estate',
    status: CaseStatus.PENDING,
    priority: 'medium',
    dueDate: new Date(2025, 6, 10),
    documents: [],
    createdAt: new Date(2023, 4, 5),
    updatedAt: new Date(2023, 6, 15),
  },
  {
    id: '4',
    clientId: '456',
    clientName: 'Maria Garcia',
    title: 'Corporate Merger Review',
    description: 'Review of proposed merger between ABC Corp and XYZ Inc',
    category: 'Corporate Law',
    status: CaseStatus.IN_PROGRESS,
    priority: 'high',
    dueDate: new Date(2025, 5, 30),
    documents: [],
    createdAt: new Date(2023, 8, 5),
    updatedAt: new Date(2023, 8, 10),
  },
  {
    id: '5',
    clientId: '789',
    clientName: 'David Lee',
    title: 'Tax Liability Assessment',
    description: 'Review of tax implications for international business operations',
    category: 'Tax Law',
    status: CaseStatus.NEW,
    priority: 'medium',
    dueDate: new Date(2025, 6, 5),
    documents: [],
    createdAt: new Date(2023, 8, 12),
    updatedAt: new Date(2023, 8, 12),
  }
];

export const mockAppointments: Appointment[] = [
  {
    id: '1',
    title: 'Initial Consultation',
    lawyerName: 'You',
    clientName: 'John Doe',
    date: new Date(2025, 4, 15, 10, 30),
    status: 'scheduled',
  },
  {
    id: '2',
    title: 'Contract Review',
    lawyerName: 'You',
    clientName: 'Jane Smith',
    date: new Date(2025, 4, 18, 14, 0),
    status: 'confirmed',
  },
  {
    id: '3',
    title: 'Case Strategy Discussion',
    lawyerName: 'You',
    clientName: 'Robert Johnson',
    date: new Date(2025, 4, 20, 11, 15),
    status: 'scheduled',
  }
];
